name: Build and Deploy to Bunny CDN

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build Jekyll Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            /nix/var/nix/db
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.nix', 'flake.lock', 'Gemfile.lock', 'gemset.nix') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Build with Nix Flake
        run: nix build

      - name: Prepare site for upload
        run: |
          mkdir -p _site_output
          cp -r result/* _site_output/

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: built-site
          path: _site_output/
          retention-days: 1

  deploy:
    name: Deploy to Bunny CDN
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download built site
        uses: actions/download-artifact@v4
        with:
          name: built-site
          path: _site

      - name: Deploy to Bunny
        uses: R-J-dev/bunny-deploy@v2.0.6
        with:
          access-key: ${{ secrets.BUNNY_ACCESS_KEY }}
          directory-to-upload: _site
          storage-endpoint: "https://storage.bunnycdn.com"
          storage-zone-name: "stefn"
          storage-zone-password: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
          concurrency: "5"
          enable-delete-action: true
          enable-purge-pull-zone: true
          pull-zone-id: 4582976
          replication-timeout: "15000"